services:
  modelmaker:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: model-maker-api
    networks:
      - db
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env
    environment:
      - PORT=3333
      - LOG_LEVEL=info
      - GOOGLE_CREDENTIALS_FILE=./service-account-key.json
    ports:
      - "3333:3333"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    environment:
      - TZ=${TIMEZONE}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_NAMESPACE=auth
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - db
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-saml@everbit.dev}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-changeme}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5432:80"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  caddy:
    image: caddy
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-:80}
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/caddy/data:/data
      - ./docker/caddy/config:/config
    networks:
      db:
        aliases:
          - db.soupmodelmaker.local
          - soupmodelmaker.local
          - api.local
          - soupmodelmaker.org
          - api.soupmodelmaker.org

volumes:
  postgres_data:
  pgadmin:

networks:
  db:
